Project Synapse {
  database_type: 'Sql Server'
  Host: 'asd'
  Note: '''
    # Azure Synapse Database for D365
    ### Host: `asatst1-ondemand.sql.azuresynapse.net`
    ### Editor: [https://github.dev/aquzif/AWG-database-docs](https://github.dev/aquzif/AWG-database-docs)
  '''
}




Table SalesTable {
    SalesId string [default: "N012345/23/000001",note: "Numer zamówienia sprzedaży"]
    AngGlazingQty int [note: "Ilość szklen na nagłówku"]
    AngQuotationId string [default: "1234567890", note: "Numer oferty z PREF"]
    WorkerSalesResponsible int [note: "ID Osoby odpowiedzialnej za zamówienie"]
    CustAccount string [default: "N012345", note: "Numer klienta"]
    SalesName string [ note: "Nazwa klienta"]
    SalesStatus SalesStatus [note: "Stan zamówienia"]
    AngSalesOrderStatus AngSalesOrderStatus [note: "Status zamówienia"]
    TaxGroup string [note: "Kod grupy podatkowej"]
    DeliveryPostalAddress String 
    note: "Tabela z nagłówkami zamówienia"
}

Table SalesLine {
    SalesId string [note: "Numer zamówienia sprzedaży"]
    SalesQty int [note: "Ilość na zamówieniu sprzedaży"]
    CurrencyCode string [note: "3 - znakowy kod waluty"]
    SalesPrice decimal [note: "Cena netto na zamówieniu sprzedaży w walucie"]
    inventDimId string
    "(WIDOK) SalesGrossPrice" decimal [note: "Cena brutto na zamówieniu sprzedaży w walucie (WIP)"]
    "(PBI) Szklenia Per Okno" int [note: "Ilość szkleń dla pojedyńczego okna w wierszu"]
    "(PBI) Szklenia Per Wariant" int [note: "Ilość szkleń dla całego wiersza "]
    note: "Tabela z pozycjami zamówienia"
}

Table InventDim {
    inventDimId string
    configId string
    note: "Wymiary magazynowe"
}

Table EcoResConfiguration {
    Name string [note: "Nazwa konfiguracji np. N10024/23/0000901-"]
    AngProductCategoryId string [note: "Kategoria produktu"]
    AngGlassesQuantity int [note: "Ilość szklen danej konfiguracji"]
    note: "Tabela z konfiguracjami wierszy zamówień"
}

Table DirPartyTable {
    RecId string [note: "ID Osoby"]
    Name string [note: "Nazwa osoby"]
    note: "Globalna książka adresowa"
}

Table CustTable {
    AccountNum string [note: "Numer klienta"]
    SalesDistrictId string [note: "Grupa klienta np. GRUPA 1, GRUPA 2 itd."]
    note: "Tabela z danymi klientów"
}

Table CaseDetailBase {
    CaseId string [note: "Numer sprawy"]
    ComplaintNumber string [note: "Numer reklamacji"]
    note: "Sprawy i reklamacje"
}

Table CaseDetail {
    CaseId string [note: "Numer sprawy"]
    note: "Szczegóły sprawy/reklamacji"
}

Table AngCaseDetailComplaint{
    AccountNum string [note: "Numer klienta"]
    IndustryCode string [note: "Grupa klienta np. GRUPA 1, GRUPA 2 itd."]
    note: "Tabela uzupełniająca CaseDetails reklamacji"
}

Table WHSLoadTable{
    LoadId string [note: "Identfikator załadunku (z TMS)"]
    LoadSchedShipUTCDateTime datetime [note: "Data i godzina zaplanowanej wysyłki ładunku"]
    note: "Tabela z nagłówkami załadunków"
}

Table WHSLoadLine{
    LoadId string [note: "Identfikator załadunku (z TMS)"]
    OrderNum string [note: "Numer zamówienia sprzedaży"]
    note: "Tabela z wierszami transportowymi - zamówieniami"
}

Table ProdTable {
    DlvDate datetime [note: "Data produkcji"]
    SchedDate datetime [note: "Planowana data zdania"]
    ProdId string [note: "Numer zlecenia produkcyjnego"]
    CollectRefProdId string [note: "Numer zlecenia produkcyjnego z którego zostało utworzone"]
    ProdGroupId string [note: "Linia produkcyjna"]
    InventRefId string [note: "Numer odwołania"]
    note: "Tabela ze zleceniami produkcyjnymi"
}

Table ProdJournalProd {
    AngWindowNumber string [note: "Numer pozycji produkowanej (np. kiedy jest 1, u nas będzie 001)"]
    ProdId string [note: "Numer zlecenia produkcyjnego"]
    JournalId string
}

Table ProdJournalTable {
    JournalId string
    PostedDateTime datetime [note: "data skanu na MWG"]
}

Table CustTrans {
    AmountCur string [note: "Nazwa waluty"]
    MCRPaymOrderID string [note: "Numer zamówienia sprzedaży"] 
    Invoice string [note: "Numer faktury"]
}

Table PurchTable {
    PurchId string [note: "Numer zamówienia zakupu"]
    CurrencyCode string [note: "Kod waluty"]
    "(WIDOK) ExchangeRate" string [note: "Kurs waluty zastosowany do zamówienia"]
    note: "Tabela z nagłówkami zamówień zakupów"
}

Table PurchLine {
    PurchId string [note: "Numer zamówienia zakupu"]
    ItemId string [note: "Numer artykułu"]
    PurchQty decimal [note: "Ilosć zamówionego artykułu"]
    PriceUnit decimal [note: "Cena per jednostka"]
    "(PBI) PriceNetto" decimal [note: "Cena netto wiersza w walucie"]
    "(PBI) PriceNettoPLN" decimal [note: "Cena netto wiersza w PLN"]
    note: "Tabela z wierszami zamówienia zakupu"
}

Table TaxGroupHeading {
    TaxGroup string [note: "Kod grupy podatkowej"]
    note: "Tabela z grupami podatkowymi"
}

Table ExchangeRateCurrencyPair {
    RECID int [note: "Identyfikator rekordu"]
    FromCurrencyCode string [note: "Waluta źródłowa kursu"]
    ToCurrencyCode string [note: "Waluta docelowa kursu"]
    ExchangeRateType string [note: "Identyfikator typu kursu"]
    note: "Tabela z identyfikatoramui parami zmian walutowych"
}

Table ExchangeRate {
    ExchangeRateCurrencyPair string [note: "Identyfikator tabeli nadrzędnej"]
    ValidFrom datetime [note: "Kurs ważny od"]
    ValidTo datetime [note: "Kurs ważny do"]
    ExchangeRate decimal [note: "Kurs waluty `trzeba podzielić przez 100`"]
    note: "Tabela z kursami przewalutowań"
}

Table AngSalesConfirmations {
    SalesId string [note: "Numer zamówienia którego dotyczą potwierdzenia"]
    SpecialistConfirmation bit [note: "Wartość 0/1, czy specjalista musi potwierdzić"]
    CustomerConfirmation bit [note: "Wartość 0/1, czy klient musi potwierdzić"]
    AdvanceConfirmation bit [note: "Wartość 0/1, czy musi wpłacić zaliczkę"]
    AttendantConfirmation bit [note: "Wartość 0/1, czy opiekun musi potwierdzić"]
    SpecialistConfirmed bit [note: "Wartość 0/1, potwierdzone przez specjalistę/konstruktora?"]
    CustomerConfirmed bit [note: "Wartość 0/1, potwierdzone przez klienta"]
    AdvanceConfirmed bit [note: "Wartość 0/1, czy wpłacona zaliczka"]
    AttendantConfirmed bit [note: "Wartość 0/1, czy potwierdzone przez opiekuna"]
    SpecialistConfirmedUser string [note: "Użytkownik który potwierdził specjalistę"]
    CustomerConfirmedUser string [note: "Użytkownik który potwierdził klienta"]
    AdvanceConfirmedUser string [note: "Użytkownik który potwierdził zaliczkę"]
    AttendantConfirmedUser string [note: "Użytkownik który potwierdził opiekuna"]
    SpecialistConfirmedDateTime datetime [note: "Data i godzina, kiedy zostało potwierdzone przez specjalistę"]
    CustomerConfirmedDateTime datetime [note: "Data i godzina, kiedy zostało potwierdzone przez klienta"]
    AdvanceConfirmedDateTime datetime [note: "Data i godzina, kiedy została potwierdzona płatność zaliczki"]
    AttendantConfirmedDateTime datetime [note: "Data i godzina, kliedy zostało powierdzone przez opiekuna"]
    "(PBI) SpecialistConfirmedDate" date [note: "Data, kiedy zostało potwierdzone przez specjalistę"]
    "(PBI) CustomerConfirmedDate" date [note: "Data, kiedy zostało potwierdzone przez klienta"]
    "(PBI) AdvanceConfirmedDate" date [note: "Data, kiedy została potwierdzona płatność zaliczki"]
    "(PBI) AttendantConfirmedDate" date [note: "Data, kliedy zostało powierdzone przez opiekuna"]
    note: "Tabela z potwierdzeniami do zamówienia"
}

Table LogisticsPostalAddress {
    RECID int [note: "Identyfikator wiersza"]
    Address string [note: "Adres (w jednej linii, z enterami)"]
    CountryRegionId string [note: "Identyfikator kraju (3-znakowy kod kraju)"]
    City string [note: "Miasto"]
    Latitude decimal [note: "Szerokość geograficzna"]
    Longitude decimal [note: "Wysokość geograficzna"]
    Street string [note: "Ulica, numer domu itd..."]
    ZipCode string [note: "Kod pocztowy"]
    note: "Tabela z adresami logistycznymi"
}


Ref: "SalesTable"."SalesId" < "SalesLine"."SalesId"
Ref: "SalesTable"."SalesId" - "AngSalesConfirmations"."SalesId"
Ref: "SalesTable"."DeliveryPostalAddress" < "LogisticsPostalAddress"."RECID"
Ref: "SalesLine"."inventDimId" < "InventDim"."inventDimId"  
Ref: "EcoResConfiguration"."Name" < "InventDim"."configId"  
Ref: "SalesTable"."WorkerSalesResponsible" < "DirPartyTable"."RecId"  
Ref: "SalesTable"."CustAccount" < "CustTable"."AccountNum"  
Ref: "CaseDetailBase"."CaseId" < "CaseDetail"."CaseId"
Ref: "WHSLoadTable"."LoadId" < "WHSLoadLine"."LoadId" 
Ref: "SalesTable"."SalesId" - "WHSLoadLine"."OrderNum"
Ref: "ProdTable"."ProdId" < "ProdJournalProd"."ProdId"
Ref: "EcoResConfiguration"."Name" < "ProdTable"."ProdId"  
Ref: "ProdJournalTable"."JournalId" < "ProdJournalProd"."JournalId"
Ref: "SalesTable"."SalesId" < "CustTrans"."MCRPaymOrderID"
Ref: "PurchTable"."PurchId" < "PurchLine"."PurchId"
Ref: "SalesTable"."TaxGroup" < "TaxGroupHeading"."TaxGroup"
Ref: "ExchangeRateCurrencyPair"."RECID" < "ExchangeRate"."ExchangeRateCurrencyPair"


enum SalesStatus {
    "0 - Brak"
    "1 - Otwarte"
    "2 - Dostarczone"
    "3 - Zafakturowane"
    "4 - Anuloowane"
    // 1 [note: "Otwarte"]
    // 2 [note: "Dostarczone"]
    // 3 [note: "Zafakturowane"]
    // 4 [note: "Anuloowane"]
}

enum AngSalesOrderStatus {
    "0 - Przyjęte"
    "1 - Zarejestrowane"
    "2 - Korekta"
    "3 - Przekazane do wyjaśnienia"
    "4 - Dorabiana technologia"
    "5 - Wstrzymane przez klienta"
    "6 - Niespełnione minimum logistyczne"
    "7 - Wstrzymane przez Dział Windykacji"
    "8 - Przekracza limit"
    "9 - Niekompletne"
}